export type CnoEntry = {
  clave: string
  denominacion: string
  esArea: boolean
}

export const CNO_CATALOG: CnoEntry[] = [
  { clave: "01", denominacion: "Cultivo, crianza y aprovechamiento", esArea: true },
  { clave: "01.1", denominacion: "Agricultura y silvicultura", esArea: false },
  { clave: "01.2", denominacion: "Ganadería", esArea: false },
  { clave: "01.3", denominacion: "Pesca y acuacultura", esArea: false },
  { clave: "02", denominacion: "Extracción y suministro", esArea: true },
  { clave: "02.1", denominacion: "Exploración", esArea: false },
  { clave: "02.2", denominacion: "Extracción", esArea: false },
  { clave: "02.3", denominacion: "Refinación y beneficio", esArea: false },
  { clave: "02.4", denominacion: "Provisión de energía", esArea: false },
  { clave: "02.5", denominacion: "Provisión de agua", esArea: false },
  { clave: "03", denominacion: "Construcción", esArea: true },
  { clave: "03.1", denominacion: "Planeación y dirección de obras", esArea: false },
  { clave: "03.2", denominacion: "Edificación y urbanización", esArea: false },
  { clave: "03.3", denominacion: "Acabado", esArea: false },
  { clave: "03.4", denominacion: "Instalación y mantenimiento", esArea: false },
  { clave: "04", denominacion: "Tecnología", esArea: true },
  { clave: "04.1", denominacion: "Mecánica", esArea: false },
  { clave: "04.2", denominacion: "Electricidad", esArea: false },
  { clave: "04.3", denominacion: "Electrónica", esArea: false },
  { clave: "04.4", denominacion: "Informática", esArea: false },
  { clave: "04.5", denominacion: "Telecomunicaciones", esArea: false },
  { clave: "04.6", denominacion: "Procesos industriales", esArea: false },
  { clave: "05", denominacion: "Procesamiento y fabricación", esArea: true },
  { clave: "05.1", denominacion: "Minerales no metálicos", esArea: false },
  { clave: "05.2", denominacion: "Metales", esArea: false },
  { clave: "05.3", denominacion: "Alimentos y bebidas", esArea: false },
  { clave: "05.4", denominacion: "Textiles y prendas de vestir", esArea: false },
  { clave: "05.5", denominacion: "Materia orgánica", esArea: false },
  { clave: "05.6", denominacion: "Productos químicos", esArea: false },
  { clave: "05.7", denominacion: "Productos metálicos y de hule y plástico", esArea: false },
  { clave: "05.8", denominacion: "Productos eléctricos y electrónicos", esArea: false },
  { clave: "05.9", denominacion: "Productos impresos", esArea: false },
  { clave: "06", denominacion: "Transporte", esArea: true },
  { clave: "06.1", denominacion: "Ferroviario", esArea: false },
  { clave: "06.2", denominacion: "Autotransporte", esArea: false },
  { clave: "06.3", denominacion: "Aéreo", esArea: false },
  { clave: "06.4", denominacion: "Marítimo y fluvial", esArea: false },
  { clave: "06.5", denominacion: "Servicios de apoyo", esArea: false },
  { clave: "07", denominacion: "Provisión de bienes y servicios", esArea: true },
  { clave: "07.1", denominacion: "Comercio", esArea: false },
  { clave: "07.2", denominacion: "Alimentación y hospedaje", esArea: false },
  { clave: "07.3", denominacion: "Turismo", esArea: false },
  { clave: "07.4", denominacion: "Deporte y esparcimiento", esArea: false },
  { clave: "07.5", denominacion: "Servicios personales", esArea: false },
  {
    clave: "07.6",
    denominacion: "Reparación de artículos de uso doméstico y personal",
    esArea: false,
  },
  { clave: "07.7", denominacion: "Limpieza", esArea: false },
  { clave: "07.8", denominacion: "Servicio postal y mensajería", esArea: false },
  { clave: "08", denominacion: "Gestión y soporte administrativo", esArea: true },
  { clave: "08.1", denominacion: "Bolsa, banca y seguros", esArea: false },
  { clave: "08.2", denominacion: "Administración", esArea: false },
  { clave: "08.3", denominacion: "Servicios legales", esArea: false },
  { clave: "09", denominacion: "Salud y protección social", esArea: true },
  { clave: "09.1", denominacion: "Servicios médicos", esArea: false },
  { clave: "09.2", denominacion: "Inspección sanitaria y del medio ambiente", esArea: false },
  { clave: "09.3", denominacion: "Seguridad social", esArea: false },
  { clave: "09.4", denominacion: "Protección de bienes y/o personas", esArea: false },
  { clave: "10", denominacion: "Comunicación", esArea: true },
  { clave: "10.1", denominacion: "Publicación", esArea: false },
  { clave: "10.2", denominacion: "Radio, cine, televisión y teatro", esArea: false },
  { clave: "10.3", denominacion: "Interpretación artística", esArea: false },
  { clave: "10.4", denominacion: "Traducción e interpretación lingüística", esArea: false },
  { clave: "10.5", denominacion: "Publicidad, propaganda y relaciones públicas", esArea: false },
  { clave: "11", denominacion: "Desarrollo y extensión del conocimiento", esArea: true },
  { clave: "11.1", denominacion: "Investigación", esArea: false },
  { clave: "11.2", denominacion: "Enseñanza", esArea: false },
  { clave: "11.3", denominacion: "Difusión cultural", esArea: false },
]

export const CNO_AREAS = CNO_CATALOG.filter((e) => e.esArea)
